cabal-version:      3.0
name:               prophunt-multiplayer
version:            0.1.0.0
build-type:         Simple

executable prophunt-server
  main-is:          PropHuntServer.hs
  other-modules:    PropHuntv2
  hs-source-dirs:   .
  default-language: Haskell2010
  ghc-options:      -Wall
  build-depends:
      aeson >= 2.0
    , base >= 4.14 && < 5
    , bytestring
    , containers
    , websockets >= 0.12
